name: GitHub Pages

   on:
     push:
       branches:
         - main  # Set a branch name to trigger deployment

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2

         - name: Setup Rust
           uses: actions-rs/toolchain@v1
           with:
             profile: minimal
             toolchain: stable
             override: true

         - name: Install wasm-pack
           run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

         - name: Build
           run: wasm-pack build --target web

         - name: Deploy
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: .
